fix: use old version of cozy-konnector-libs and pdfjs
pdfjs : there was a font error message :
TypeError: Cannot read property 'slice' of undefined
    at new OTFFontFactory (/home/doubleface/Workspace/connectors/booking.com/node_modules/pdfjs/lib/font/otf.js:19:25)
    at Object.<anonymous> (/home/doubleface/Workspace/connectors/booking.com/src/html2pdf.js:4:23)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/doubleface/Workspace/connectors/booking.com/src/index.js:21:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

cozy-konnector-libs : regression on requestFactory, no more bills found